# Generated by Django 3.2.8 on 2021-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
